# Configuration for Scroll pHAT HD Clock

## Disable separator blink
#blink: true
#
## Rotate the display
#rotate: 0
#
## Enable the clock only between these times
#schedule:
#  start_time:  8:00
#  end_time:   18:00
